spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ebank
    username: root
    password:
  mvc:
    cors:
      allowed-origins: "*"
      allowed-methods: GET, POST, PUT, DELETE, OPTIONS
      allowed-headers: "*"
      allow-credentials: true
      max-age: 3600
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: MYSQL
    database-platform: org.hibernate.dialect.MySQLDialect
logging:
  level:
    root: INFO
jwt:
  expiration: 3600000 # 1 hour in milliseconds
  secret: t46lhpZ4NO46PYo2i/i5EQhacnV7dukT3JT5NIi6o1N8j+SRVTY7TzBitG8DmQjg0GOJNhAzQXVTRfamUpRZIg==